"use client";

import React, { useState, useEffect } from "react";
import {
  Globe,
  CheckCircle2,
  AlertTriangle,
  Send,
  Lock,
  Code2,
  RefreshCw,
  ExternalLink,
  Copy,
  Check,
  Sparkles,
  Info,
  Server,
  Layers,
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import type { SafeSiteProfile } from "@/lib/sanitize";
import { testWebhookPingAction, updateTenantWebhookAction } from "@/lib/serverActions";

export type CmsPlatformId = "wordpress" | "shopify" | "webflow" | "ghost" | "custom";

interface CmsConnectorModalProps {
  platform: CmsPlatformId | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  profile: SafeSiteProfile;
  onEndpointSaved: (newUrl: string) => void;
}

interface PlatformMeta {
  title: string;
  badge: string;
  badgeColor: string;
  desc: string;
  docsUrl: string;
  defaultEndpoint: string;
  instructions: string[];
}

const PLATFORM_CONFIGS: Record<CmsPlatformId, PlatformMeta> = {
  wordpress: {
    title: "WordPress Auto-Publisher",
    badge: "WordPress REST API",
    badgeColor: "bg-blue-600/10 text-blue-400 border-blue-500/20",
    desc: "Publishes structured HTML articles directly to your WordPress posts via standard REST endpoints or webhook receivers.",
    docsUrl: "https://developer.wordpress.org/rest-api/reference/posts/",
    defaultEndpoint: "https://yourblog.com/wp-json/wp/v2/posts",
    instructions: [
      "In your WordPress Admin, go to Users > Profile > Application Passwords.",
      "Enter Application Name 'AI Blog SaaS' and click 'Add New Application Password'.",
      "Copy the 24-character password generated by WordPress.",
      "Input your WordPress URL below or use an automation plugin (WP Webhooks / Zapier) as your receiver URL.",
    ],
  },
  shopify: {
    title: "Shopify Store Blog",
    badge: "Shopify Admin API",
    badgeColor: "bg-emerald-600/10 text-emerald-400 border-emerald-500/20",
    desc: "Dispatches SEO articles straight to your Shopify Online Store blog articles endpoint.",
    docsUrl: "https://shopify.dev/docs/api/admin-rest/latest/resources/article",
    defaultEndpoint: "https://your-store.myshopify.com/admin/api/2024-01/blogs/BLOG_ID/articles.json",
    instructions: [
      "In Shopify Admin, go to Settings > Apps and sales channels > Develop apps.",
      "Create an app named 'AI Blog SaaS Publisher'.",
      "In Configuration, grant 'write_content' and 'read_content' Admin API permissions.",
      "Install the app and copy your Admin API access token (starts with shpat_).",
    ],
  },
  webflow: {
    title: "Webflow CMS Collections",
    badge: "Webflow REST API v2",
    badgeColor: "bg-indigo-600/10 text-indigo-400 border-indigo-500/20",
    desc: "Creates new CMS items inside your Webflow Blog Collection with automated slugging and rich semantic HTML.",
    docsUrl: "https://developers.webflow.com/data/reference/cms/items/create-item",
    defaultEndpoint: "https://api.webflow.com/v2/collections/COLLECTION_ID/items",
    instructions: [
      "In Webflow Workspace Settings, navigate to Integrations > API Access.",
      "Click 'Generate API Token' and copy your Bearer Token.",
      "In Webflow Designer, open your CMS Collections settings to copy your Blog Collection ID.",
      "Configure your Webhook URL or Make/Zapier bridge below.",
    ],
  },
  ghost: {
    title: "Ghost CMS Publisher",
    badge: "Ghost Admin API v5",
    badgeColor: "bg-purple-600/10 text-purple-400 border-purple-500/20",
    desc: "Pushes published posts or drafts straight into Ghost CMS with mobiledoc and full HTML rendering.",
    docsUrl: "https://ghost.org/docs/admin-api/",
    defaultEndpoint: "https://your-blog.ghost.io/ghost/api/admin/posts/?source=html",
    instructions: [
      "In your Ghost Admin, click Settings (gear icon) > Integrations.",
      "Scroll down to Custom Integrations and click 'Add custom integration'.",
      "Name it 'AI Blog SaaS' and click Create.",
      "Copy the Admin API Key and API URL to route post payloads.",
    ],
  },
  custom: {
    title: "Custom HTTP Webhook",
    badge: "Generic JSON HTTP POST",
    badgeColor: "bg-amber-600/10 text-amber-400 border-amber-500/20",
    desc: "Dispatches signed HMAC-SHA256 payloads to any server, Next.js route, cloud function, or Make/Zapier webhook.",
    docsUrl: "https://docs.github.com/en/webhooks",
    defaultEndpoint: "https://yourwebsite.com/api/webhooks/incoming-article",
    instructions: [
      "Set up an HTTP POST endpoint on your server that accepts application/json.",
      "Read the 'x-saas-signature' header (format: sha256=<hex_hash>).",
      "Verify the cryptographic signature using HMAC-SHA256 with your site secret.",
      "Process the article payload and return HTTP 200 within 5 seconds.",
    ],
  },
};

export function CmsConnectorModal({
  platform,
  open,
  onOpenChange,
  profile,
  onEndpointSaved,
}: CmsConnectorModalProps) {
  const currentKey = platform || "wordpress";
  const meta = PLATFORM_CONFIGS[currentKey];

  const [activeTab, setActiveTab] = useState<"wizard" | "schema" | "test">("wizard");
  const [targetEndpoint, setTargetEndpoint] = useState(profile.webhook_url || meta.defaultEndpoint);
  const [postAsDraft, setPostAsDraft] = useState(true);
  const [authCredential, setAuthCredential] = useState("");
  const [copiedSample, setCopiedSample] = useState(false);

  // Live Ping Testing state
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState<{
    success: boolean;
    statusCode?: number;
    latencyMs?: number;
    message: string;
  } | null>(null);

  // Save state
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  // Sync endpoint default when platform changes
  useEffect(() => {
    if (profile.webhook_url) {
      setTargetEndpoint(profile.webhook_url);
    } else {
      setTargetEndpoint(meta.defaultEndpoint);
    }
    setTestResult(null);
    setSaveError(null);
    setSaveSuccess(false);
  }, [platform, profile.webhook_url, meta.defaultEndpoint]);

  if (!platform) return null;

  const handleTestPing = async () => {
    if (!targetEndpoint.trim()) return;
    setIsTesting(true);
    setTestResult(null);

    try {
      const res = await testWebhookPingAction(profile.id, targetEndpoint);
      setTestResult(res);
    } catch (err: any) {
      setTestResult({
        success: false,
        message: err?.message || "Failed to execute webhook test ping.",
      });
    } finally {
      setIsTesting(false);
    }
  };

  const handleSaveEndpoint = async () => {
    if (!targetEndpoint.trim()) return;
    setIsSaving(true);
    setSaveError(null);
    setSaveSuccess(false);

    try {
      const res = await updateTenantWebhookAction(profile.id, targetEndpoint.trim());
      if (res.success) {
        setSaveSuccess(true);
        onEndpointSaved(targetEndpoint.trim());
        setTimeout(() => {
          setSaveSuccess(false);
          onOpenChange(false);
        }, 1800);
      } else {
        setSaveError(res.error || "Failed to save webhook endpoint.");
      }
    } catch (err: any) {
      setSaveError(err?.message || "Unexpected failure saving webhook.");
    } finally {
      setIsSaving(false);
    }
  };

  const samplePayload = {
    event: "article.published",
    site_id: profile.id,
    site_name: profile.site_name,
    domain: profile.domain,
    article: {
      title: "10 Proven SEO Strategies for Rapid SaaS Growth in 2026",
      metaDescription: "Discover actionable organic growth frameworks and semantic search optimization tactics...",
      content: "<article><h2>The Shift to Semantic Search</h2><p>Modern search algorithms demand topical depth...</p></article>",
      suggestedTags: ["SaaS Growth", "SEO", "Content Marketing"],
      wordCount: 1420,
      readingTimeMinutes: 7,
    },
    telemetry: {
      provider: "groq",
      model: "llama-3.3-70b-versatile",
      latency_ms: 1240,
    },
    timestamp: new Date().toISOString(),
  };

  const copyPayloadJson = () => {
    navigator.clipboard.writeText(JSON.stringify(samplePayload, null, 2));
    setCopiedSample(true);
    setTimeout(() => setCopiedSample(false), 2000);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="border-border/80 bg-card/95 backdrop-blur-2xl max-w-2xl p-6 max-h-[90vh] flex flex-col">
        {/* Header */}
        <DialogHeader className="shrink-0 pb-2">
          <div className="flex items-center justify-between gap-3 mb-1">
            <div className="flex items-center gap-2">
              <div className="h-7 w-7 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
                <Globe className="h-4 w-4 text-primary" />
              </div>
              <DialogTitle className="text-lg font-bold text-foreground">
                {meta.title}
              </DialogTitle>
            </div>
            <Badge variant="outline" className={`text-[10px] font-mono ${meta.badgeColor}`}>
              {meta.badge}
            </Badge>
          </div>
          <DialogDescription className="text-xs text-muted-foreground">
            {meta.desc}
          </DialogDescription>
        </DialogHeader>

        {/* Tab Navigation */}
        <Tabs
          value={activeTab}
          onValueChange={(v) => setActiveTab(v as any)}
          className="flex-1 flex flex-col min-h-0"
        >
          <TabsList className="grid grid-cols-3 bg-muted/60 p-1 mb-4 shrink-0">
            <TabsTrigger value="wizard" className="text-xs font-semibold">
              Setup Wizard
            </TabsTrigger>
            <TabsTrigger value="schema" className="text-xs font-semibold">
              Payload Schema
            </TabsTrigger>
            <TabsTrigger value="test" className="text-xs font-semibold">
              Live Ping Test
            </TabsTrigger>
          </TabsList>

          {/* TAB 1: Setup Wizard */}
          <TabsContent value="wizard" className="space-y-4 flex-1 overflow-y-auto pr-1">
            {/* Step-by-Step Guide */}
            <div className="rounded-xl border border-border/60 bg-background/50 p-3.5 space-y-2.5">
              <div className="flex items-center justify-between text-xs font-bold text-foreground">
                <span className="flex items-center gap-1.5">
                  <Info className="h-4 w-4 text-indigo-400" />
                  Quick Setup Guide (30 Seconds)
                </span>
                <a
                  href={meta.docsUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="text-[11px] text-primary hover:underline flex items-center gap-1 font-normal"
                >
                  <span>Official Docs</span>
                  <ExternalLink className="h-3 w-3" />
                </a>
              </div>

              <ol className="list-decimal list-inside space-y-1.5 text-[11px] text-muted-foreground leading-relaxed">
                {meta.instructions.map((step, idx) => (
                  <li key={idx} className="pl-1">
                    <span className="text-foreground/90">{step}</span>
                  </li>
                ))}
              </ol>
            </div>

            {/* Target Endpoint Input */}
            <div className="space-y-2">
              <label className="text-xs font-semibold text-foreground flex items-center justify-between">
                <span>Webhook Delivery URL</span>
                <span className="text-[10px] text-muted-foreground font-mono">HTTP POST</span>
              </label>
              <Input
                value={targetEndpoint}
                onChange={(e) => setTargetEndpoint(e.target.value)}
                placeholder="https://yourblog.com/api/webhooks/incoming"
                className="font-mono text-xs bg-background/80 h-9"
              />
              <p className="text-[10px] text-muted-foreground">
                Our servers will dispatch an HTTP POST request to this URL every time a new article finishes generation.
              </p>
            </div>

            {/* Platform Options */}
            <div className="rounded-xl border border-border/50 bg-background/30 p-3.5 space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-xs font-semibold text-foreground">Publish as Draft first</div>
                  <div className="text-[11px] text-muted-foreground">
                    Recommended: review article in CMS before pushing to live public readers.
                  </div>
                </div>
                <Switch checked={postAsDraft} onCheckedChange={setPostAsDraft} />
              </div>

              <div className="pt-2 border-t border-border/40 flex items-center justify-between text-[11px]">
                <span className="text-muted-foreground flex items-center gap-1">
                  <Lock className="h-3 w-3 text-amber-400" />
                  Payload HMAC-SHA256 signature enabled
                </span>
                <Badge variant="outline" className="font-mono text-[9px] text-emerald-400 border-emerald-500/30">
                  x-saas-signature
                </Badge>
              </div>
            </div>

            {saveSuccess && (
              <div className="rounded-lg bg-emerald-500/10 border border-emerald-500/20 p-3 text-xs text-emerald-300 flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0" />
                <span>Integration activated! Articles will now auto-publish to this endpoint.</span>
              </div>
            )}

            {saveError && (
              <div className="rounded-lg bg-red-500/10 border border-red-500/20 p-3 text-xs text-red-300 flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-red-400 shrink-0" />
                <span>{saveError}</span>
              </div>
            )}
          </TabsContent>

          {/* TAB 2: Payload Schema */}
          <TabsContent value="schema" className="space-y-3 flex-1 overflow-y-auto pr-1">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-foreground">
                JSON Body Dispatched on Publish Event
              </span>
              <Button
                variant="outline"
                size="sm"
                onClick={copyPayloadJson}
                className="h-7 text-xs gap-1 border-border/60"
              >
                {copiedSample ? (
                  <>
                    <Check className="h-3.5 w-3.5 text-emerald-400" />
                    <span>Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="h-3.5 w-3.5 text-muted-foreground" />
                    <span>Copy Schema</span>
                  </>
                )}
              </Button>
            </div>

            <div className="rounded-xl border border-border/70 bg-black/90 p-4 font-mono text-[11px] overflow-x-auto max-h-72">
              <pre className="text-emerald-300 leading-relaxed">
                {JSON.stringify(samplePayload, null, 2)}
              </pre>
            </div>

            <div className="rounded-lg border border-border/50 bg-background/50 p-2.5 text-[11px] text-muted-foreground space-y-1">
              <span className="font-semibold text-foreground block">Request Headers Included:</span>
              <div className="font-mono text-[10px] space-y-0.5 text-indigo-300">
                <div>Content-Type: application/json</div>
                <div>x-saas-event: article.published</div>
                <div>x-saas-signature: sha256=&lt;hmac_hash&gt;</div>
              </div>
            </div>
          </TabsContent>

          {/* TAB 3: Live Ping Test */}
          <TabsContent value="test" className="space-y-4 flex-1 overflow-y-auto pr-1">
            <div className="rounded-xl border border-border/60 bg-background/50 p-4 space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-xs font-bold text-foreground">Verify Endpoint Reachability</h4>
                  <p className="text-[11px] text-muted-foreground mt-0.5">
                    Sends an authentic signed HTTP POST ping with sample article payload to confirm your receiver returns HTTP 200.
                  </p>
                </div>
                <Button
                  size="sm"
                  onClick={handleTestPing}
                  disabled={isTesting || !targetEndpoint}
                  className="text-xs font-semibold gap-1.5 shrink-0"
                >
                  {isTesting ? (
                    <>
                      <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                      Pinging...
                    </>
                  ) : (
                    <>
                      <Send className="h-3.5 w-3.5 text-indigo-300" />
                      Execute Test Ping
                    </>
                  )}
                </Button>
              </div>

              <div className="font-mono text-xs text-muted-foreground truncate bg-background p-2 rounded border border-border/40">
                Target: {targetEndpoint}
              </div>
            </div>

            {testResult && (
              <div
                className={`rounded-xl border p-4 space-y-2 text-xs animate-in fade-in duration-200 ${
                  testResult.success
                    ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-300"
                    : "bg-red-500/10 border-red-500/30 text-red-300"
                }`}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 font-bold">
                    {testResult.success ? (
                      <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0" />
                    ) : (
                      <AlertTriangle className="h-4 w-4 text-red-400 shrink-0" />
                    )}
                    <span>{testResult.success ? "Connection Verified" : "Ping Unsuccessful"}</span>
                  </div>

                  {testResult.latencyMs && (
                    <Badge variant="outline" className="font-mono text-[10px]">
                      {testResult.latencyMs}ms roundtrip
                    </Badge>
                  )}
                </div>

                <p className="text-[11px] leading-relaxed text-foreground/90">
                  {testResult.message}
                </p>
              </div>
            )}
          </TabsContent>
        </Tabs>

        {/* Footer */}
        <DialogFooter className="shrink-0 border-t border-border/40 pt-4 flex sm:justify-between items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => onOpenChange(false)}
            className="text-xs"
          >
            Cancel
          </Button>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleTestPing}
              disabled={isTesting || !targetEndpoint}
              className="text-xs border-border/70"
            >
              {isTesting ? "Testing..." : "Test Ping"}
            </Button>

            <Button
              size="sm"
              onClick={handleSaveEndpoint}
              disabled={isSaving || !targetEndpoint.trim()}
              className="text-xs font-semibold px-4 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white"
            >
              {isSaving ? "Saving..." : "Save & Activate"}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
